### ISSUE TITLE
Impossible to install dato (couchdb issue)

### ISSUE THREAD

**Issue by davidszerman** [YunoHost-Apps/dato_ynh#25]
Hello, 

i have installed couchdb app on Yunohost, on its own subdomain, with ssl certificate (not self signed) (nothing else done)

When I want to install dato making the link with couchdb, i have got this error : 

[Error] Please make sure that your couchdb instance is accessible from the url you provided, with a proper SSL certificate (not a self-signed one), otherwise you will not be able to login to dato!

Did I miss something else ?

**Comment by davidszerman** [comment]
The admin password ("admin" username) is correct ; I was able to connect to it via my webbrowser ; the URI of  https://squeak.eauchat.org/apps/dato/ seems to be offline

Additional details : 

Installation de dato...
Validating installation parameters...
Storing installation settings...
Finding an available port...
Installing dependencies...
dpkg: warning: version 'v8.0.1' has bad syntax: version number does not start with digit
Configuring system user...
Setting up source files...
Configuring NGINX web server...
Building node dependencies...
npm WARN deprecated uuid@3.2.1: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
Configuring a systemd service...
Generating dato config files...
Customizing couch config...
Setting up admin user in couch...
[Error] There was an error creating the dato admin user for in couch. You will probably have to do it manually (check the last section of this page for instructions: https://squeak.eauchat.org/apps/dato/?setups).
[Error] Here is the error message from couchdb:
[Error]
502 Bad Gateway
nginx
[Error] Please make sure that your couchdb instance is accessible from the url you provided, with a proper SSL certificate (not a self-signed one), otherwise you will not be able to login to dato!
% Total % Received % Xferd Average Speed Time Time Time Current

**Comment by eauchat** [comment]
It seems that there is a problem with the access to your couchdb server. Is it accessible from the outside? If you enter the url of your couchdb in the browser, what does it display?
Are those error interrupting the installation of dato? Or is the install finishing anyway?

(If you need, the links to dato's documentation should now work again.)

**Comment by davidszerman** [comment]
Hi,

yes it is accessible as I was able to connect to the couchdb server with the admin url (so login and passwords are fine too   ;)  )

It stops the installation of the software, indeed.

David

**Comment by eauchat** [comment]
Hello David,
Sorry for the delay in answering.

I'm a bit confused about the problem you're having. It seems that your couchdb instance is answering to a 502 error code, when dato is trying to create it's admin user. Usually, when I have such kind of issue on yunohost, it's related to a problem with the availability of the service I installed, it's not started or something.
So since you say couchdb is working for you, I don't really get why this is happening. And also, normally this shouldn't stop the install process, so I'm a bit confused

One thing you could try is to install dato without auto-synchronization of the databases, see if that work, and then enable auto-synchronization manually.
To do so, install dato, choose not to enable auto-synchronization, open the app on the domain you chose, and you should be able to access it, similarly to how it's [here](https://publicdato.eauchat.org).
Then, to enable auto-synchronization, you basically have to manually do what the install script is doing in [those lines](https://github.com/YunoHost-Apps/dato_ynh/blob/master/scripts/install#L158-L208).
In short, it means:
 - adding [this file](https://github.com/YunoHost-Apps/dato_ynh/blob/master/conf/couch.ini) to `/opt/couchdb/etc/local.d/dato.ini` (don't forget to replace `https://__DOMAIN__` in the template file by the url at which you installed dato)
 - modifying the `config/private.js` file where dato is installed replacing it by [this file](https://github.com/YunoHost-Apps/dato_ynh/blob/master/conf/private-autosync.js), replacing all `__VARIABLES__` by the appropriate password/username... (I'm not 100% sure where the dato folder is in yunohost, but I believe in `/opt/yunohst/dato` or something like this)
 - manually adding your dato admin user in the couchdb `_users` database and making sure it has `"dato-admin"` role
 - adding `"dato"` and `"dato-admin"` roles as members of the `_users` database

That should be all. Normally the install script takes care of this process automatically, but there seems to be something going wrong in your situation.

Hope that helps :/

**Comment by eauchat** [comment]
Hello David,
Did you eventually manage to troubleshoot the issue and install dato?

**Comment by eauchat** [comment]
I'll assume this issue has been solved.
If someone has/had similar problems, feel free to open a new issue or to post further in this one.
